##
# node.js installation (latest stable instead of Ubuntu's out-of-date one)
#
- name: Node.js | Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed
  tags: nodejs

- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list
  tags: nodejs

- name: Node.js | Update the apt cache for the new repository
  action: apt update-cache=yes
  tags: nodejs

- name: Node.js | Install nodejs and npm
  action: apt pkg=$item state=installed
  tags: nodejs
  with_items:
    - nodejs
    - npm
